[tool.black]
line-length = 120
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term --cov-report=html"
testpaths = ["tests"]
pythonpath = ["src"]